--Inserts 

--CLIENTE--
INSERT ALL
INTO CLIENTE ( ENDERECO, CIDADE, UF, TELEFONE_PRINCIPAL, COD_PEDIDO) VALUES ( 'AV. BRASIL OESTE, 123', 'PASSO FUNDO', 'RS', 5433143434,1)
INTO CLIENTE (ENDERECO, CIDADE, UF, TELEFONE_PRINCIPAL, COD_PEDIDO) VALUES ( 'AV. PRESIDENTE VERGAS, 4545', 'PASSO FUNDO', 'RS', 5433111212,2)
INTO CLIENTE ( ENDERECO, CIDADE, UF, TELEFONE_PRINCIPAL, COD_PEDIDO) VALUES ( 'AV. PAULISTA, 78', 'SÃO PAULO', 'SP', 01132324556,3)
INTO CLIENTE ( ENDERECO, CIDADE, UF, TELEFONE_PRINCIPAL, COD_PEDIDO) VALUES ( 'AV. TIMBUCA, 888', 'SANTA CATARINA', 'SC',04845454545,4)
SELECT * FROM DUAL;


--CATEGORIA--

INSERT ALL
INTO CATEGORIA ( NOME, DESCRICAO) VALUES ( 'CANECAS', 'CANECAS COLORIDAS')
INTO CATEGORIA ( NOME, DESCRICAO) VALUES ( 'CAMISETAS', 'CAMISETAS COLORIDAS')
INTO CATEGORIA ( NOME, DESCRICAO) VALUES ( 'CANETAS', 'CANETAS PERSONALIZADAS')
INTO CATEGORIA ( NOME, DESCRICAO) VALUES ( 'MOCHILA', 'MOCHILA NOTEBOOK')
SELECT * FROM DUAL;


--PRODUTO--
INSERT ALL
INTO PRODUTO ( NOME, STATUS, PRECO_UNITARIO, COR, COD_CATEGORIA) VALUES ('CANECA 1',1,10.00,'VERDE',1)
INTO PRODUTO ( NOME, STATUS, PRECO_UNITARIO, COR, COD_CATEGORIA) VALUES ('CANECA 2',1,15.00,'VERMELHA',1)
INTO PRODUTO ( NOME, STATUS, PRECO_UNITARIO, COR, COD_CATEGORIA) VALUES ('CANECA 3',1,18.00,'AMARELA',1)
INTO PRODUTO ( NOME, STATUS, PRECO_UNITARIO, COR, COD_CATEGORIA) VALUES ('CANECA 4',0,20.00,'PRETO',1)
SELECT * FROM DUAL;

--ESTOQUE--
INSERT ALL
INTO ESTOQUE ( cod_produto, QUANTIDADE, ESTOQUE_MINIMO) VALUES (1,3,1)
INTO ESTOQUE ( cod_produto, QUANTIDADE, ESTOQUE_MINIMO) VALUES (2,10,3)
INTO ESTOQUE ( cod_produto, QUANTIDADE, ESTOQUE_MINIMO) VALUES (3,10,1)
INTO ESTOQUE ( cod_produto, QUANTIDADE, ESTOQUE_MINIMO) VALUES (4,15,3)
SELECT * FROM DUAL;

--PEDIDO--
INSERT ALL
INTO PEDIDO ( DATA_PEDIDO, PRAZO_ENTREGA, DATA_ENVIO, DATA_ENTREGA, VALOR_FRETE, DESCONTO, COD_CLIENTE, COD_PRODUTO) 
VALUES (TO_DATE('2016/05/03', 'yyyy/mm/dd'),10,TO_DATE('2016/05/05', 'yyyy/mm/dd'),TO_DATE('2016/05/20', 'yyyy/mm/dd'), 15.00,10,1,1)

INTO PEDIDO (DATA_PEDIDO, PRAZO_ENTREGA, DATA_ENVIO, DATA_ENTREGA, VALOR_FRETE, DESCONTO, COD_CLIENTE, COD_PRODUTO) 
VALUES (TO_DATE('2016/06/03', 'yyyy/mm/dd'),10,TO_DATE('2016/06/05', 'yyyy/mm/dd'),TO_DATE('2016/06/20', 'yyyy/mm/dd'), 20.00,5,2,2)

INTO PEDIDO ( DATA_PEDIDO, PRAZO_ENTREGA, DATA_ENVIO, DATA_ENTREGA, VALOR_FRETE, DESCONTO, COD_CLIENTE, COD_PRODUTO) 
VALUES (TO_DATE('2016/07/03', 'yyyy/mm/dd'),10,TO_DATE('2016/07/05', 'yyyy/mm/dd'),TO_DATE('2016/07/20', 'yyyy/mm/dd'), 18.00,4,1,1)

INTO PEDIDO (DATA_PEDIDO, PRAZO_ENTREGA, DATA_ENVIO, DATA_ENTREGA, VALOR_FRETE, DESCONTO, COD_CLIENTE, COD_PRODUTO) 
VALUES (TO_DATE('2016/08/03', 'yyyy/mm/dd'),10,TO_DATE('2016/08/05', 'yyyy/mm/dd'),TO_DATE('2016/08/20', 'yyyy/mm/dd'), 25.00,8,4,3)

SELECT * FROM DUAL;

--PEDIDO ENTREGA--

INSERT ALL
INTO PEDIDO_ENTREGA (COD_PEDIDO, NOME_DESTINATARIO, ENDERECO_DESTINATARIO, CIDADE, UF, CEP) VALUES (1,'PEDRO', 'AV. BRASIL OESTE, 123', 'PASSO FUNDO', 'RS', 99100001)
INTO PEDIDO_ENTREGA (COD_PEDIDO, NOME_DESTINATARIO, ENDERECO_DESTINATARIO, CIDADE, UF, CEP) VALUES (2,'MARIA', 'AV. PRESIDENTE VERGAS, 4545', 'PASSO FUNDO', 'RS', 99100123)
INTO PEDIDO_ENTREGA (COD_PEDIDO, NOME_DESTINATARIO, ENDERECO_DESTINATARIO, CIDADE, UF, CEP) VALUES (3,'JOÃO', 'AV. PAULISTA, 78', 'SÃO PAULO', 'SP', 98300555)
INTO PEDIDO_ENTREGA (COD_PEDIDO, NOME_DESTINATARIO, ENDERECO_DESTINATARIO, CIDADE, UF, CEP) VALUES (4,'JUREMA', 'AV. TIMBUCA, 888', 'SANTA CATARINA', 'SC', 93100000)
SELECT * FROM DUAL;

--PRODUTO_PEDIDO--

INSERT ALL
INTO PRODUTO_PEDIDO (COD_PRODUTO, COD_PEDIDO, QUANTIDADE, DESCONTO) VALUES (1,1,2,10)
INTO PRODUTO_PEDIDO (COD_PRODUTO, COD_PEDIDO, QUANTIDADE, DESCONTO) VALUES (2,2,1,5)
INTO PRODUTO_PEDIDO (COD_PRODUTO, COD_PEDIDO, QUANTIDADE, DESCONTO) VALUES (3,3,2,4)
INTO PRODUTO_PEDIDO (COD_PRODUTO, COD_PEDIDO, QUANTIDADE, DESCONTO) VALUES (4,4,3,8)
SELECT * FROM DUAL;



--FRETE--
INSERT ALL 
INTO FRETE ( CIDADE, UF, VALOR, PRAZO) VALUES (1,'PASSO FUNDO', 'RS', 20.00, 10)
INTO FRETE ( CIDADE, UF, VALOR, PRAZO) VALUES (2,'RIO DE JANEIRO', 'RS', 20.00, 15)
INTO FRETE ( CIDADE, UF, VALOR, PRAZO) VALUES (3,'SÃO PAULO', 'RS', 20.00, 15)
INTO FRETE ( CIDADE, UF, VALOR, PRAZO) VALUES (4,'SANTA CATARINA', 'SC', 20.00, 10)
SELECT * FROM DUAL;


--FORNECEDOR--
INSERT ALL 	
INTO FORNECEDORES ( NOME, ENDERECO, CIDADE, UF, CEP, PAIS, TELEFONE) VALUES ('FORNECEDOR 1', 'AV. AVENIDA 1', 'SÃO PAULO', 'SP', 99230000, 'BRASIL', 11333239090)
INTO FORNECEDORES ( NOME, ENDERECO, CIDADE, UF, CEP, PAIS, TELEFONE) VALUES ('FORNECEDOR 2', 'AV. AVENIDA 2', 'SÃO PAULO', 'SP', 99230111, 'BRASIL', 11334455667)
INTO FORNECEDORES ( NOME, ENDERECO, CIDADE, UF, CEP, PAIS, TELEFONE) VALUES ('FORNECEDOR 3', 'AV. AVENIDA 3', 'SANTA CATARINA', 'SC', 99030120, 'BRASIL', 4533349706)
INTO FORNECEDORES ( NOME, ENDERECO, CIDADE, UF, CEP, PAIS, TELEFONE) VALUES ('FORNECEDOR 5', 'AV. AVENIDA 5', 'PARANÁ', 'PR', 98090123, 'BRASIL', 11333238888)
SELECT * FROM DUAL;